package com.aos.mapper;

import com.aos.pojo.BreakdownInfo;
import com.aos.pojo.BreakdownInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BreakdownInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int countByExample(BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByExample(BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insert(BreakdownInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insertSelective(BreakdownInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    List<BreakdownInfo> selectByExampleWithBLOBs(BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    List<BreakdownInfo> selectByExample(BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    BreakdownInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExampleSelective(@Param("record") BreakdownInfo record, @Param("example") BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") BreakdownInfo record, @Param("example") BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExample(@Param("record") BreakdownInfo record, @Param("example") BreakdownInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKeySelective(BreakdownInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(BreakdownInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table breakdown_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKey(BreakdownInfo record);
}