package com.aos.mapper;

import com.aos.pojo.DictOperationType;
import com.aos.pojo.DictOperationTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictOperationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int countByExample(DictOperationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByExample(DictOperationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByPrimaryKey(Integer operationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insert(DictOperationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insertSelective(DictOperationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    List<DictOperationType> selectByExample(DictOperationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    DictOperationType selectByPrimaryKey(Integer operationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExampleSelective(@Param("record") DictOperationType record, @Param("example") DictOperationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExample(@Param("record") DictOperationType record, @Param("example") DictOperationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKeySelective(DictOperationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKey(DictOperationType record);
}