package com.aos.mapper;

import com.aos.pojo.OperationInfo;
import com.aos.pojo.OperationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int countByExample(OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByExample(OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insert(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int insertSelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    List<OperationInfo> selectByExampleWithBLOBs(OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    List<OperationInfo> selectByExample(OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    OperationInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExampleSelective(@Param("record") OperationInfo record, @Param("example") OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("record") OperationInfo record, @Param("example") OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByExample(@Param("record") OperationInfo record, @Param("example") OperationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKeySelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    int updateByPrimaryKey(OperationInfo record);
}