package com.aos.pojo;

import java.util.Date;

public class BreakdownInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.system_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.system_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.subsystem_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer subsystemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.subsystem_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String subsystemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.device_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.device_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.affect_beam_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date affectBeamTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.entered_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date enteredTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date durationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.is_continue
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String isContinue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column breakdown_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.id
     *
     * @return the value of breakdown_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.id
     *
     * @param id the value for breakdown_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.user_id
     *
     * @return the value of breakdown_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.user_id
     *
     * @param userId the value for breakdown_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.user_name
     *
     * @return the value of breakdown_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.user_name
     *
     * @param userName the value for breakdown_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.operation_type
     *
     * @return the value of breakdown_info.operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.operation_type
     *
     * @param operationType the value for breakdown_info.operation_type
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.system_id
     *
     * @return the value of breakdown_info.system_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.system_id
     *
     * @param systemId the value for breakdown_info.system_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setSystemId(Integer systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.system_name
     *
     * @return the value of breakdown_info.system_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.system_name
     *
     * @param systemName the value for breakdown_info.system_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName == null ? null : systemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.subsystem_id
     *
     * @return the value of breakdown_info.subsystem_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getSubsystemId() {
        return subsystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.subsystem_id
     *
     * @param subsystemId the value for breakdown_info.subsystem_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setSubsystemId(Integer subsystemId) {
        this.subsystemId = subsystemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.subsystem_name
     *
     * @return the value of breakdown_info.subsystem_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getSubsystemName() {
        return subsystemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.subsystem_name
     *
     * @param subsystemName the value for breakdown_info.subsystem_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setSubsystemName(String subsystemName) {
        this.subsystemName = subsystemName == null ? null : subsystemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.device_id
     *
     * @return the value of breakdown_info.device_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.device_id
     *
     * @param deviceId the value for breakdown_info.device_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.device_name
     *
     * @return the value of breakdown_info.device_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.device_name
     *
     * @param deviceName the value for breakdown_info.device_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.start_time
     *
     * @return the value of breakdown_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.start_time
     *
     * @param startTime the value for breakdown_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.end_time
     *
     * @return the value of breakdown_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.end_time
     *
     * @param endTime the value for breakdown_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.affect_beam_time
     *
     * @return the value of breakdown_info.affect_beam_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getAffectBeamTime() {
        return affectBeamTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.affect_beam_time
     *
     * @param affectBeamTime the value for breakdown_info.affect_beam_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setAffectBeamTime(Date affectBeamTime) {
        this.affectBeamTime = affectBeamTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.entered_time
     *
     * @return the value of breakdown_info.entered_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getEnteredTime() {
        return enteredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.entered_time
     *
     * @param enteredTime the value for breakdown_info.entered_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setEnteredTime(Date enteredTime) {
        this.enteredTime = enteredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.duration_time
     *
     * @return the value of breakdown_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getDurationTime() {
        return durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.duration_time
     *
     * @param durationTime the value for breakdown_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDurationTime(Date durationTime) {
        this.durationTime = durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.is_continue
     *
     * @return the value of breakdown_info.is_continue
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getIsContinue() {
        return isContinue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.is_continue
     *
     * @param isContinue the value for breakdown_info.is_continue
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setIsContinue(String isContinue) {
        this.isContinue = isContinue == null ? null : isContinue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column breakdown_info.description
     *
     * @return the value of breakdown_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column breakdown_info.description
     *
     * @param description the value for breakdown_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}