package com.aos.pojo;

public class DictOperationType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_operation_type.operation_type_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer operationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_operation_type.operation_type_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String operationTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_operation_type.operation_type_id
     *
     * @return the value of dict_operation_type.operation_type_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getOperationTypeId() {
        return operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_operation_type.operation_type_id
     *
     * @param operationTypeId the value for dict_operation_type.operation_type_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setOperationTypeId(Integer operationTypeId) {
        this.operationTypeId = operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_operation_type.operation_type_name
     *
     * @return the value of dict_operation_type.operation_type_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getOperationTypeName() {
        return operationTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_operation_type.operation_type_name
     *
     * @param operationTypeName the value for dict_operation_type.operation_type_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setOperationTypeName(String operationTypeName) {
        this.operationTypeName = operationTypeName == null ? null : operationTypeName.trim();
    }
}