package com.aos.pojo;

import java.util.Date;

public class OperationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date durationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.id
     *
     * @return the value of operation_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.id
     *
     * @param id the value for operation_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.user_id
     *
     * @return the value of operation_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.user_id
     *
     * @param userId the value for operation_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.user_name
     *
     * @return the value of operation_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.user_name
     *
     * @param userName the value for operation_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.start_time
     *
     * @return the value of operation_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.start_time
     *
     * @param startTime the value for operation_info.start_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.end_time
     *
     * @return the value of operation_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.end_time
     *
     * @param endTime the value for operation_info.end_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.duration_time
     *
     * @return the value of operation_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getDurationTime() {
        return durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.duration_time
     *
     * @param durationTime the value for operation_info.duration_time
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDurationTime(Date durationTime) {
        this.durationTime = durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_info.description
     *
     * @return the value of operation_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_info.description
     *
     * @param description the value for operation_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}