package com.aos.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SummaryInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public SummaryInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andPrepareIsNull() {
            addCriterion("prepare is null");
            return (Criteria) this;
        }

        public Criteria andPrepareIsNotNull() {
            addCriterion("prepare is not null");
            return (Criteria) this;
        }

        public Criteria andPrepareEqualTo(Integer value) {
            addCriterion("prepare =", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareNotEqualTo(Integer value) {
            addCriterion("prepare <>", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareGreaterThan(Integer value) {
            addCriterion("prepare >", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareGreaterThanOrEqualTo(Integer value) {
            addCriterion("prepare >=", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareLessThan(Integer value) {
            addCriterion("prepare <", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareLessThanOrEqualTo(Integer value) {
            addCriterion("prepare <=", value, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareIn(List<Integer> values) {
            addCriterion("prepare in", values, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareNotIn(List<Integer> values) {
            addCriterion("prepare not in", values, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareBetween(Integer value1, Integer value2) {
            addCriterion("prepare between", value1, value2, "prepare");
            return (Criteria) this;
        }

        public Criteria andPrepareNotBetween(Integer value1, Integer value2) {
            addCriterion("prepare not between", value1, value2, "prepare");
            return (Criteria) this;
        }

        public Criteria andBeamIsNull() {
            addCriterion("beam is null");
            return (Criteria) this;
        }

        public Criteria andBeamIsNotNull() {
            addCriterion("beam is not null");
            return (Criteria) this;
        }

        public Criteria andBeamEqualTo(Integer value) {
            addCriterion("beam =", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamNotEqualTo(Integer value) {
            addCriterion("beam <>", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamGreaterThan(Integer value) {
            addCriterion("beam >", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamGreaterThanOrEqualTo(Integer value) {
            addCriterion("beam >=", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamLessThan(Integer value) {
            addCriterion("beam <", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamLessThanOrEqualTo(Integer value) {
            addCriterion("beam <=", value, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamIn(List<Integer> values) {
            addCriterion("beam in", values, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamNotIn(List<Integer> values) {
            addCriterion("beam not in", values, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamBetween(Integer value1, Integer value2) {
            addCriterion("beam between", value1, value2, "beam");
            return (Criteria) this;
        }

        public Criteria andBeamNotBetween(Integer value1, Integer value2) {
            addCriterion("beam not between", value1, value2, "beam");
            return (Criteria) this;
        }

        public Criteria andResearchIsNull() {
            addCriterion("research is null");
            return (Criteria) this;
        }

        public Criteria andResearchIsNotNull() {
            addCriterion("research is not null");
            return (Criteria) this;
        }

        public Criteria andResearchEqualTo(Integer value) {
            addCriterion("research =", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchNotEqualTo(Integer value) {
            addCriterion("research <>", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchGreaterThan(Integer value) {
            addCriterion("research >", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchGreaterThanOrEqualTo(Integer value) {
            addCriterion("research >=", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchLessThan(Integer value) {
            addCriterion("research <", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchLessThanOrEqualTo(Integer value) {
            addCriterion("research <=", value, "research");
            return (Criteria) this;
        }

        public Criteria andResearchIn(List<Integer> values) {
            addCriterion("research in", values, "research");
            return (Criteria) this;
        }

        public Criteria andResearchNotIn(List<Integer> values) {
            addCriterion("research not in", values, "research");
            return (Criteria) this;
        }

        public Criteria andResearchBetween(Integer value1, Integer value2) {
            addCriterion("research between", value1, value2, "research");
            return (Criteria) this;
        }

        public Criteria andResearchNotBetween(Integer value1, Integer value2) {
            addCriterion("research not between", value1, value2, "research");
            return (Criteria) this;
        }

        public Criteria andShutdownIsNull() {
            addCriterion("shutdown is null");
            return (Criteria) this;
        }

        public Criteria andShutdownIsNotNull() {
            addCriterion("shutdown is not null");
            return (Criteria) this;
        }

        public Criteria andShutdownEqualTo(Integer value) {
            addCriterion("shutdown =", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownNotEqualTo(Integer value) {
            addCriterion("shutdown <>", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownGreaterThan(Integer value) {
            addCriterion("shutdown >", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownGreaterThanOrEqualTo(Integer value) {
            addCriterion("shutdown >=", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownLessThan(Integer value) {
            addCriterion("shutdown <", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownLessThanOrEqualTo(Integer value) {
            addCriterion("shutdown <=", value, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownIn(List<Integer> values) {
            addCriterion("shutdown in", values, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownNotIn(List<Integer> values) {
            addCriterion("shutdown not in", values, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownBetween(Integer value1, Integer value2) {
            addCriterion("shutdown between", value1, value2, "shutdown");
            return (Criteria) this;
        }

        public Criteria andShutdownNotBetween(Integer value1, Integer value2) {
            addCriterion("shutdown not between", value1, value2, "shutdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownIsNull() {
            addCriterion("breakdown is null");
            return (Criteria) this;
        }

        public Criteria andBreakdownIsNotNull() {
            addCriterion("breakdown is not null");
            return (Criteria) this;
        }

        public Criteria andBreakdownEqualTo(Integer value) {
            addCriterion("breakdown =", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownNotEqualTo(Integer value) {
            addCriterion("breakdown <>", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownGreaterThan(Integer value) {
            addCriterion("breakdown >", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownGreaterThanOrEqualTo(Integer value) {
            addCriterion("breakdown >=", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownLessThan(Integer value) {
            addCriterion("breakdown <", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownLessThanOrEqualTo(Integer value) {
            addCriterion("breakdown <=", value, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownIn(List<Integer> values) {
            addCriterion("breakdown in", values, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownNotIn(List<Integer> values) {
            addCriterion("breakdown not in", values, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownBetween(Integer value1, Integer value2) {
            addCriterion("breakdown between", value1, value2, "breakdown");
            return (Criteria) this;
        }

        public Criteria andBreakdownNotBetween(Integer value1, Integer value2) {
            addCriterion("breakdown not between", value1, value2, "breakdown");
            return (Criteria) this;
        }

        public Criteria andOtherIsNull() {
            addCriterion("other is null");
            return (Criteria) this;
        }

        public Criteria andOtherIsNotNull() {
            addCriterion("other is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEqualTo(Integer value) {
            addCriterion("other =", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotEqualTo(Integer value) {
            addCriterion("other <>", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThan(Integer value) {
            addCriterion("other >", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherGreaterThanOrEqualTo(Integer value) {
            addCriterion("other >=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThan(Integer value) {
            addCriterion("other <", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherLessThanOrEqualTo(Integer value) {
            addCriterion("other <=", value, "other");
            return (Criteria) this;
        }

        public Criteria andOtherIn(List<Integer> values) {
            addCriterion("other in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotIn(List<Integer> values) {
            addCriterion("other not in", values, "other");
            return (Criteria) this;
        }

        public Criteria andOtherBetween(Integer value1, Integer value2) {
            addCriterion("other between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andOtherNotBetween(Integer value1, Integer value2) {
            addCriterion("other not between", value1, value2, "other");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table summary_info
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 24 10:03:46 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table summary_info
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}