package com.aos.pojo;

import java.util.Date;

public class SummaryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.prepare
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer prepare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.beam
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer beam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.research
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer research;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.shutdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer shutdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.breakdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer breakdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.other
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.update_at
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column summary_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.id
     *
     * @return the value of summary_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.id
     *
     * @param id the value for summary_info.id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.user_id
     *
     * @return the value of summary_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.user_id
     *
     * @param userId the value for summary_info.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.user_name
     *
     * @return the value of summary_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.user_name
     *
     * @param userName the value for summary_info.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.prepare
     *
     * @return the value of summary_info.prepare
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getPrepare() {
        return prepare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.prepare
     *
     * @param prepare the value for summary_info.prepare
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setPrepare(Integer prepare) {
        this.prepare = prepare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.beam
     *
     * @return the value of summary_info.beam
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getBeam() {
        return beam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.beam
     *
     * @param beam the value for summary_info.beam
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setBeam(Integer beam) {
        this.beam = beam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.research
     *
     * @return the value of summary_info.research
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getResearch() {
        return research;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.research
     *
     * @param research the value for summary_info.research
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setResearch(Integer research) {
        this.research = research;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.shutdown
     *
     * @return the value of summary_info.shutdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getShutdown() {
        return shutdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.shutdown
     *
     * @param shutdown the value for summary_info.shutdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setShutdown(Integer shutdown) {
        this.shutdown = shutdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.breakdown
     *
     * @return the value of summary_info.breakdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getBreakdown() {
        return breakdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.breakdown
     *
     * @param breakdown the value for summary_info.breakdown
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setBreakdown(Integer breakdown) {
        this.breakdown = breakdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.other
     *
     * @return the value of summary_info.other
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Integer getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.other
     *
     * @param other the value for summary_info.other
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setOther(Integer other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.update_at
     *
     * @return the value of summary_info.update_at
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.update_at
     *
     * @param updateAt the value for summary_info.update_at
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column summary_info.description
     *
     * @return the value of summary_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column summary_info.description
     *
     * @param description the value for summary_info.description
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}