package com.aos.pojo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString

public class SysUser {
    private String password;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.phone
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.department
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.role_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.role_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_id
     *
     * @return the value of sys_user.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public Integer getUserId() {
//        return userId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_id
     *
     * @param userId the value for sys_user.user_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setUserId(Integer userId) {
//        this.userId = userId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public String getEmail() {
//        return email;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setEmail(String email) {
//        this.email = email == null ? null : email.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.phone
     *
     * @return the value of sys_user.phone
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public String getPhone() {
//        return phone;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.phone
     *
     * @param phone the value for sys_user.phone
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setPhone(String phone) {
//        this.phone = phone == null ? null : phone.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.department
     *
     * @return the value of sys_user.department
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public String getDepartment() {
//        return department;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.department
     *
     * @param department the value for sys_user.department
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setDepartment(String department) {
//        this.department = department == null ? null : department.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role_name
     *
     * @return the value of sys_user.role_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public String getRoleName() {
//        return roleName;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role_name
     *
     * @param roleName the value for sys_user.role_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setRoleName(String roleName) {
//        this.roleName = roleName == null ? null : roleName.trim();
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.role_id
     *
     * @return the value of sys_user.role_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public Integer getRoleId() {
//        return roleId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.role_id
     *
     * @param roleId the value for sys_user.role_id
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setRoleId(Integer roleId) {
//        this.roleId = roleId;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public String getUserName() {
//        return userName;
//    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated Sun Nov 24 10:03:46 CST 2024
     */
//    public void setUserName(String userName) {
//        this.userName = userName == null ? null : userName.trim();
//    }
}